### ISSUE TITLE
Question: Does openapi-response-validator support v3 schemas?

### ISSUE THREAD

**Issue by dosyara** [kogosoftwarellc/open-api#269]
I'm doing some tests with OpenAPI v3 and cannot figure out how to validate response object with `validateResponse`.
I use:
"express": "^4.16.3",
"express-openapi": "^3.3.0",

I have `openapi: "3.0.0"` schema yalm file. File itself is valid according to v3 validator.
Paths section looks like this:
```
paths:
  /test:
    get:
      responses:
        "200":
          description: test path
          content:
            application/json:
              schema:
                type: object
                  required:
                    - id
                    - date
                  properties:
                    id:
                      type: string
                    date:
                      type: string
```

When I run 
```js
res.validateResponse(statusCode, responseObject)
```
for a valid response object, I get:
```js
{ message: 'The response was not valid.',
  errors:
   [ { errorCode: 'type.openapi.responseValidation',
       message: 'response should be null' } ] }
```

So my question is: is this happens because of lack of support by response validator or am I doing something wrong?

**Comment by jsdevel** [comment]
@dosyara this may have been fixed by @funduck in https://github.com/kogosoftwarellc/open-api/pull/222.  I just published it.  Can you try it out?

**Comment by dosyara** [comment]
Tried, no luck.
 Updated express-openapi to 3.4.0, and still get `response should be null`.

**Comment by jsdevel** [comment]
what arguments are you passing to validateResponse?

**Comment by dosyara** [comment]
I pass: two parameters: 200 (`statusCode`) and { my json response } ( `responseObject`).
I've experimented with different response objects, the only thing which not generates error is `null`

**Comment by funduck** [comment]
pushed to #224, hope I did it right and @jsdevel will soon accept my request

**Comment by jsdevel** [comment]
you did @funduck !  try with the latest @dosyara

**Comment by dosyara** [comment]
Updated to express-openapi@3.5.0 it now works with inlined schemas!
But have an issue with references. I get an error if schema is defined in components:
```
{ message: 'The response was not valid.',
  errors:
   [ { errorCode: '$ref.openapi.responseValidation',
       message:
        'response can\'t resolve reference #/components/schemas/test' } ] }
```
For this schema:
```
openapi: "3.0.0"
paths:
  /test:
    get:
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test'

components:
  schemas:
    test:
      type: object
      required:
        - id
      properties:
        id:
          type: string
```

Schema validator says it's valid tho

**Comment by jsdevel** [comment]
Ok.  Please open a PR.

**Comment by jsdevel** [comment]
@dosyara i'm going to close this as the original issue was fixed.  if you have other issues, please open up new issues or better yet PRs!  thanks for contributing!
